baseURL = 'https://afrose-techy-trade-blog.netlify.app/'
languageCode = 'en-us'
title = 'Techy Trade Blog'
theme = 'hugo-papermod'

# Enable Emoji for fun
enableEmoji = true

[params]
  description = "Complete guide to tech trading and money making strategies"
  defaultTheme = "light"
  # homeInfoMode = "custom"  # Uncomment for custom home layout
  
  [params.assets]
    favicon = "/favicon.ico"
    # theme_color = "#6c5ce7"  # Purple accent
  
  [params.profileMode]
    enabled = false  # Set to true if you want a profile header
  
  [params.homeInfoParams]
    Title = "Techy Trade Blog"
    Content = """
    Your complete guide to making money through tech trading. 
    Daily insights, strategies, and market analysis.
    """
  
  [params.label]
    name = "Tech Trading"
    # color = "#6c5ce7"  # Purple like Bolt site

# Social links (optional)
[social]
  # Twitter = "https://twitter.com/yourname"
  # GitHub = "https://github.com/yourname"

[menu]
  [[menu.main]]
    name = "🏠 Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "📚 Blog"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "ℹ️ About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    name = "📧 Contact"
    url = "/contact/"
    weight = 4

[services]
  [services.googleAnalytics]
    id = "GA-TRACKING-ID"
